BIN      = isShared
LIB      = -lgeUtil -lgeCore
CPPFLAGS = -std=c++1y -Wall -O3
CPP      = g++
OBJ      = main.o

all: ${BIN}

${BIN}: ${OBJ}
	${CPP} ${OBJ} -o ${BIN} ${LIB}

%.o: %.cpp %.h
	${CPP} -o $@ ${CPPFLAGS} -c $<

run: ${BIN}
	./${BIN} window \{ size [ u32 512 u32 512 ] fullscreen bool false \}

clean:
	rm -f *.o ${BIN} ${LSDIRBIN}

mem: ${BIN}
	valgrind --tool=memcheck --leak-check=yes ./${BIN}
