#include"hp.h"

using namespace ge::gl::hp;

PFNGLIMAGETRANSFORMPARAMETERIVHPPROC    glImageTransformParameterivHP    = NULL;
PFNGLGETIMAGETRANSFORMPARAMETERFVHPPROC glGetImageTransformParameterfvHP = NULL;
PFNGLGETIMAGETRANSFORMPARAMETERIVHPPROC glGetImageTransformParameterivHP = NULL;
PFNGLIMAGETRANSFORMPARAMETERIHPPROC     glImageTransformParameteriHP     = NULL;
PFNGLIMAGETRANSFORMPARAMETERFVHPPROC    glImageTransformParameterfvHP    = NULL;
PFNGLIMAGETRANSFORMPARAMETERFHPPROC     glImageTransformParameterfHP     = NULL;
