#include"intel.h"

using namespace ge::gl::intel;

PFNGLCREATEPERFQUERYINTELPROC      glCreatePerfQueryINTEL      = NULL;
PFNGLCOLORPOINTERVINTELPROC        glColorPointervINTEL        = NULL;
PFNGLENDPERFQUERYINTELPROC         glEndPerfQueryINTEL         = NULL;
PFNGLBEGINPERFQUERYINTELPROC       glBeginPerfQueryINTEL       = NULL;
PFNGLGETPERFQUERYDATAINTELPROC     glGetPerfQueryDataINTEL     = NULL;
PFNGLVERTEXPOINTERVINTELPROC       glVertexPointervINTEL       = NULL;
PFNGLGETNEXTPERFQUERYIDINTELPROC   glGetNextPerfQueryIdINTEL   = NULL;
PFNGLGETFIRSTPERFQUERYIDINTELPROC  glGetFirstPerfQueryIdINTEL  = NULL;
PFNGLMAPTEXTURE2DINTELPROC         glMapTexture2DINTEL         = NULL;
PFNGLTEXCOORDPOINTERVINTELPROC     glTexCoordPointervINTEL     = NULL;
PFNGLUNMAPTEXTURE2DINTELPROC       glUnmapTexture2DINTEL       = NULL;
PFNGLGETPERFCOUNTERINFOINTELPROC   glGetPerfCounterInfoINTEL   = NULL;
PFNGLGETPERFQUERYIDBYNAMEINTELPROC glGetPerfQueryIdByNameINTEL = NULL;
PFNGLGETPERFQUERYINFOINTELPROC     glGetPerfQueryInfoINTEL     = NULL;
PFNGLSYNCTEXTUREINTELPROC          glSyncTextureINTEL          = NULL;
PFNGLDELETEPERFQUERYINTELPROC      glDeletePerfQueryINTEL      = NULL;
PFNGLNORMALPOINTERVINTELPROC       glNormalPointervINTEL       = NULL;
