#include"mesa.h"

using namespace ge::gl::mesa;

PFNGLWINDOWPOS3SVMESAPROC  glWindowPos3svMESA  = NULL;
PFNGLWINDOWPOS4DMESAPROC   glWindowPos4dMESA   = NULL;
PFNGLWINDOWPOS4SMESAPROC   glWindowPos4sMESA   = NULL;
PFNGLWINDOWPOS3DMESAPROC   glWindowPos3dMESA   = NULL;
PFNGLWINDOWPOS2DMESAPROC   glWindowPos2dMESA   = NULL;
PFNGLWINDOWPOS2FMESAPROC   glWindowPos2fMESA   = NULL;
PFNGLWINDOWPOS2IMESAPROC   glWindowPos2iMESA   = NULL;
PFNGLRESIZEBUFFERSMESAPROC glResizeBuffersMESA = NULL;
PFNGLWINDOWPOS4IVMESAPROC  glWindowPos4ivMESA  = NULL;
PFNGLWINDOWPOS4SVMESAPROC  glWindowPos4svMESA  = NULL;
PFNGLWINDOWPOS3SMESAPROC   glWindowPos3sMESA   = NULL;
PFNGLWINDOWPOS3IVMESAPROC  glWindowPos3ivMESA  = NULL;
PFNGLWINDOWPOS3IMESAPROC   glWindowPos3iMESA   = NULL;
PFNGLWINDOWPOS2FVMESAPROC  glWindowPos2fvMESA  = NULL;
PFNGLWINDOWPOS2SVMESAPROC  glWindowPos2svMESA  = NULL;
PFNGLWINDOWPOS2IVMESAPROC  glWindowPos2ivMESA  = NULL;
PFNGLWINDOWPOS4IMESAPROC   glWindowPos4iMESA   = NULL;
PFNGLWINDOWPOS3FMESAPROC   glWindowPos3fMESA   = NULL;
PFNGLWINDOWPOS4FVMESAPROC  glWindowPos4fvMESA  = NULL;
PFNGLWINDOWPOS4FMESAPROC   glWindowPos4fMESA   = NULL;
PFNGLWINDOWPOS3DVMESAPROC  glWindowPos3dvMESA  = NULL;
PFNGLWINDOWPOS4DVMESAPROC  glWindowPos4dvMESA  = NULL;
PFNGLWINDOWPOS2SMESAPROC   glWindowPos2sMESA   = NULL;
PFNGLWINDOWPOS3FVMESAPROC  glWindowPos3fvMESA  = NULL;
PFNGLWINDOWPOS2DVMESAPROC  glWindowPos2dvMESA  = NULL;
