#pragma once

#define CL_HPP_TARGET_OPENCL_VERSION 300
#include<CL/opencl.hpp>

#include<DefineList/DefineList.h>

DEFINE_LIST(cl_platform_info,clPlatformParams,
  CL_PLATFORM_EXTENSIONS,
  CL_PLATFORM_NAME      ,
  CL_PLATFORM_PROFILE   ,
  CL_PLATFORM_VENDOR    ,
  CL_PLATFORM_VERSION   );

DEFINE_LIST(cl_device_info,clDeviceParams,
  CL_DEVICE_BUILT_IN_KERNELS    ,
  CL_DEVICE_EXTENSIONS          ,
  CL_DEVICE_MAX_WORK_ITEM_SIZES ,
  CL_DEVICE_NAME                ,
  CL_DEVICE_OPENCL_C_VERSION    ,
  CL_DEVICE_PARTITION_PROPERTIES,
  CL_DEVICE_PARTITION_TYPE      ,
  CL_DEVICE_PROFILE             ,
  CL_DEVICE_VENDOR              ,
  CL_DEVICE_VERSION             ,
  CL_DRIVER_VERSION             );

DEFINE_LIST(cl_device_partition_property,clDeviceParatitionProperty,
  CL_DEVICE_PARTITION_EQUALLY           ,
  CL_DEVICE_PARTITION_BY_COUNTS         ,
  CL_DEVICE_PARTITION_BY_AFFINITY_DOMAIN);

DEFINE_LIST(cl_device_type,clDeviceTypes,
  CL_DEVICE_TYPE_CPU        ,
  CL_DEVICE_TYPE_GPU        ,
  CL_DEVICE_TYPE_ACCELERATOR,
  CL_DEVICE_TYPE_CUSTOM     ,
  CL_DEVICE_TYPE_DEFAULT    ,
  CL_DEVICE_TYPE_ALL        );

DEFINE_LIST(cl_int,clErrorCodes,
  CL_SUCCESS                                  ,
  CL_DEVICE_NOT_FOUND                         ,
  CL_DEVICE_NOT_AVAILABLE                     ,
  CL_COMPILER_NOT_AVAILABLE                   ,
  CL_MEM_OBJECT_ALLOCATION_FAILURE            ,
  CL_OUT_OF_RESOURCES                         ,
  CL_OUT_OF_HOST_MEMORY                       ,
  CL_PROFILING_INFO_NOT_AVAILABLE             ,
  CL_MEM_COPY_OVERLAP                         ,
  CL_IMAGE_FORMAT_MISMATCH                    ,
  CL_IMAGE_FORMAT_NOT_SUPPORTED               ,
  CL_BUILD_PROGRAM_FAILURE                    ,
  CL_MAP_FAILURE                              ,
  CL_MISALIGNED_SUB_BUFFER_OFFSET             ,
  CL_EXEC_STATUS_ERROR_FOR_EVENTS_IN_WAIT_LIST,
  CL_COMPILE_PROGRAM_FAILURE                  ,
  CL_LINKER_NOT_AVAILABLE                     ,
  CL_LINK_PROGRAM_FAILURE                     ,
  CL_DEVICE_PARTITION_FAILED                  ,
  CL_KERNEL_ARG_INFO_NOT_AVAILABLE            ,
  CL_INVALID_VALUE                            ,
  CL_INVALID_DEVICE_TYPE                      ,
  CL_INVALID_PLATFORM                         ,
  CL_INVALID_DEVICE                           ,
  CL_INVALID_CONTEXT                          ,
  CL_INVALID_QUEUE_PROPERTIES                 ,
  CL_INVALID_COMMAND_QUEUE                    ,
  CL_INVALID_HOST_PTR                         ,
  CL_INVALID_MEM_OBJECT                       ,
  CL_INVALID_IMAGE_FORMAT_DESCRIPTOR          ,
  CL_INVALID_IMAGE_SIZE                       ,
  CL_INVALID_SAMPLER                          ,
  CL_INVALID_BINARY                           ,
  CL_INVALID_BUILD_OPTIONS                    ,
  CL_INVALID_PROGRAM                          ,
  CL_INVALID_PROGRAM_EXECUTABLE               ,
  CL_INVALID_KERNEL_NAME                      ,
  CL_INVALID_KERNEL_DEFINITION                ,
  CL_INVALID_KERNEL                           ,
  CL_INVALID_ARG_INDEX                        ,
  CL_INVALID_ARG_VALUE                        ,
  CL_INVALID_ARG_SIZE                         ,
  CL_INVALID_KERNEL_ARGS                      ,
  CL_INVALID_WORK_DIMENSION                   ,
  CL_INVALID_WORK_GROUP_SIZE                  ,
  CL_INVALID_WORK_ITEM_SIZE                   ,
  CL_INVALID_GLOBAL_OFFSET                    ,
  CL_INVALID_EVENT_WAIT_LIST                  ,
  CL_INVALID_EVENT                            ,
  CL_INVALID_OPERATION                        ,
  CL_INVALID_GL_OBJECT                        ,
  CL_INVALID_BUFFER_SIZE                      ,
  CL_INVALID_MIP_LEVEL                        ,
  CL_INVALID_GLOBAL_WORK_SIZE                 ,
  CL_INVALID_PROPERTY                         ,
  CL_INVALID_IMAGE_DESCRIPTOR                 ,
  CL_INVALID_COMPILER_OPTIONS                 ,
  CL_INVALID_LINKER_OPTIONS                   ,
  CL_INVALID_DEVICE_PARTITION_COUNT           );

DEFINE_LIST(cl_context_info,clContextParams,
  CL_CONTEXT_REFERENCE_COUNT,
  CL_CONTEXT_NUM_DEVICES    ,
  CL_CONTEXT_DEVICES        ,
  CL_CONTEXT_PROPERTIES     );

DEFINE_LIST(cl_context_properties,clContextProperties,
  CL_CONTEXT_PLATFORM         ,
  CL_CONTEXT_INTEROP_USER_SYNC);

DEFINE_LIST(cl_mem_flags,clMemoryFlags,
  CL_MEM_READ_WRITE     ,
  CL_MEM_WRITE_ONLY     ,
  CL_MEM_READ_ONLY      ,
  CL_MEM_USE_HOST_PTR   ,
  CL_MEM_ALLOC_HOST_PTR ,
  CL_MEM_COPY_HOST_PTR  ,
  CL_MEM_HOST_WRITE_ONLY,
  CL_MEM_HOST_READ_ONLY ,
  CL_MEM_HOST_NO_ACCESS );

DEFINE_LIST(cl_mem_object_type,clMemoryBaseImageTypes,
  CL_MEM_OBJECT_IMAGE2D,
  CL_MEM_OBJECT_IMAGE3D);

DEFINE_LIST(cl_mem_object_type,clMemoryTypes,
  CL_MEM_OBJECT_BUFFER        ,
  CL_MEM_OBJECT_IMAGE2D       ,
  CL_MEM_OBJECT_IMAGE3D       ,
  CL_MEM_OBJECT_IMAGE2D_ARRAY ,
  CL_MEM_OBJECT_IMAGE1D       ,
  CL_MEM_OBJECT_IMAGE1D_ARRAY ,
  CL_MEM_OBJECT_IMAGE1D_BUFFER);

DEFINE_LIST(cl_channel_order,clChannelOrder,
  CL_R            ,
  CL_A            ,
  CL_RG           ,
  CL_RA           ,
  CL_RGB          ,
  CL_RGBA         ,
  CL_BGRA         ,
  CL_ARGB         ,
  CL_INTENSITY    ,
  CL_LUMINANCE    ,
  CL_Rx           ,
  CL_RGx          ,
  CL_RGBx         ,
  CL_DEPTH        ,
  CL_DEPTH_STENCIL);

DEFINE_LIST(cl_channel_type,clChannelType,
  CL_SNORM_INT8      ,
  CL_SNORM_INT16     ,
  CL_UNORM_INT8      ,
  CL_UNORM_INT16     ,
  CL_UNORM_SHORT_565 ,
  CL_UNORM_SHORT_555 ,
  CL_UNORM_INT_101010,
  CL_SIGNED_INT8     ,
  CL_SIGNED_INT16    ,
  CL_SIGNED_INT32    ,
  CL_UNSIGNED_INT8   ,
  CL_UNSIGNED_INT16  ,
  CL_UNSIGNED_INT32  ,
  CL_HALF_FLOAT      ,
  CL_FLOAT           ,
  CL_UNORM_INT24     );
